{{- if .Values.cloudProvider.aws.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectName }}-node-aws-srv
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.projectName }}-node-aws-depl
  ports:
    - port: {{ .Values.nodePort }}
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-node-aws-depl
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.projectName }}-node-aws-depl
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}-node-aws-depl
    spec:
      serviceAccountName: {{ .Values.projectName }}-node-aws-sa  
      containers:
        - name: {{ .Values.projectName }}-node-aws-depl
          image: susanssky/cpu-monitor-node-aws:latest
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
          env:
          - name: PORT
            value: {{ .Values.nodePort | quote }}
          - name: CLUSTER_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.projectName }}-secret-env
                key: cluster_name
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.projectName }}-secret-env
                key: database_url
          - name: VPC_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.projectName }}-secret-env
                key: vpc_id
          - name: NODE_GROUP_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.projectName }}-secret-env
                key: node_group_name

{{- end }}
