apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.projectName }}-secret-env
  namespace: {{ .Values.namespace }}
data:
  # both
  cluster_name: {{ .Values.deployment.node.clusterName | b64enc }}
  database_url: {{ .Values.deployment.node.databaseUrl | b64enc }}

  # eks
  vpc_id: {{ .Values.deployment.node.vpcId | b64enc }}
  node_group_name: {{ .Values.deployment.node.nodeGroupName | b64enc }}
