apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.projectName }}-secret-env
  namespace: {{ .Values.namespace }}
data:
  # both
  cluster_name: {{ .Values.deployment.node.clusterName | b64enc }}
  database_url: {{ .Values.deployment.node.databaseUrl | b64enc }}

  # aks
  subscription_id: {{ .Values.deployment.node.subscriptionId | b64enc }}
  rescource_group_name: {{ .Values.deployment.node.resourceGroupName | b64enc }}
  tenant_id: {{ .Values.deployment.node.tenantId | b64enc }}
  client_id: {{ .Values.deployment.node.clientId | b64enc }}
  client_secret: {{ .Values.deployment.node.clientSecret | b64enc }}